### ISSUE TITLE
Profiling CherryPy application

### ISSUE THREAD

**Issue by R1O** [Infinidat/dowser#2]
Hi!

I have one question about dowser usage. 
I created my own web site based on CherryPy and there is a memory leak but I don't know where it is. After searching information about my problem I understood that dowser is a great tool which can tell where the memory leak happens. 

So, in usage tutorial there are some steps that help to integrate dowser in existing CherryPy app, but I don't understand where can I see a result of memory usage? How should I use trace and chart variables?
If it is possible, can you describe dowser usage in details. 

Thanks!

**Comment by grzn** [comment]
Hi,
Sorry for the (very) late response. The results will be visible at http://127.0.0.1:8080/dowser.
